// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Firmador_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Firmador_API.Models.Configurations
{
    public partial class EmpresaConfiguration : IEntityTypeConfiguration<Empresa>
    {
        public void Configure(EntityTypeBuilder<Empresa> entity)
        {
            entity
                .HasNoKey()
                .ToTable("COM_CAT_EMPRESAS");

            entity.Property(e => e.ClaveFirma)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("CLAVE_FIRMA");
            entity.Property(e => e.CodEmpresa)
                .HasPrecision(5)
                .HasColumnName("COD_EMPRESA");
            entity.Property(e => e.CodEstado)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasColumnName("COD_ESTADO");
            entity.Property(e => e.CodPais)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasColumnName("COD_PAIS");
            entity.Property(e => e.DocRepresentante)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("DOC_REPRESENTANTE");
            entity.Property(e => e.EmpDireccion)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("EMP_DIRECCION");
            entity.Property(e => e.EmpEmail)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("EMP_EMAIL");
            entity.Property(e => e.EsquemaFinanciera)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("ESQUEMA_FINANCIERA");
            entity.Property(e => e.Logo)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("LOGO");
            entity.Property(e => e.MatriculaNotario)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("MATRICULA_NOTARIO");
            entity.Property(e => e.NbrComercial)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NBR_COMERCIAL");
            entity.Property(e => e.NbrFiscal)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NBR_FISCAL");
            entity.Property(e => e.NomNotario)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("NOM_NOTARIO");
            entity.Property(e => e.NomRepresentante)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NOM_REPRESENTANTE");
            entity.Property(e => e.Rnc)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("RNC");
            entity.Property(e => e.Rnl)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("RNL");
            entity.Property(e => e.Sello)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("SELLO");
            entity.Property(e => e.Telefono)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("TELEFONO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Empresa> entity);
    }
}
