// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Firmador_API.Models;

public partial class Empresa
{
    public short? CodEmpresa { get; set; }

    public string NbrComercial { get; set; }

    public string NbrFiscal { get; set; }

    public string Rnc { get; set; }

    public string Rnl { get; set; }

    public string EmpDireccion { get; set; }

    public string CodEstado { get; set; }

    public string CodPais { get; set; }

    public string Telefono { get; set; }

    public string EmpEmail { get; set; }

    public string DocRepresentante { get; set; }

    public string NomRepresentante { get; set; }

    public string EsquemaFinanciera { get; set; }

    public string Logo { get; set; }

    public string Sello { get; set; }

    public string NomNotario { get; set; }

    public string MatriculaNotario { get; set; }

    public string ClaveFirma { get; set; }
}